/**
 * The port's acceptance test: does this JS reproduce the Python reference?
 *
 *   npm run verify:golden
 *
 * The whole "spike in Python, app in JS" split (DECISION #16) rests on this
 * file passing. Tuned thresholds do not transfer on their own — they are only
 * meaningful alongside the exact transform that produced them. If this fails,
 * the spike's measurement does not describe the browser app, and any number in
 * spike/RESULTS.md is fiction as far as the product is concerned.
 *
 * Vectors are generated by `uv run python -m spike.export_golden`.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { hannPeriodic, spectrum, rms } from '../src/audio/dsp.js';
import { ChromaExtractor, midiToHz, noteName } from '../src/audio/chroma.js';
import { OnsetDetector } from '../src/audio/onset.js';
import { Verifier } from '../src/audio/verify.js';
import {
  DEFAULT_PARAMS,
  MIN_HISTORY_FRAMES,
  binHz,
  frameIntervalMs,
  onsetRefractoryFrames,
  stabilityFrames,
  windowSmearFrames,
  withParams,
} from '../src/audio/params.js';

const here = dirname(fileURLToPath(import.meta.url));
const golden = JSON.parse(
  readFileSync(join(here, '..', '..', 'spike', 'golden', 'golden.json'), 'utf8'),
);
const TOL = golden.tolerance;

// The exporter rounds to 9 decimal places, so no comparison can be tighter
// than half a unit in the last place. Asserting below this floor tests the
// JSON formatter, not the port.
const ROUNDING_FLOOR = 5e-10;

/** Decode base64 little-endian int16 back to floats, exactly as Python did. */
function decodeSamples(b64) {
  const bytes = Buffer.from(b64, 'base64');
  const n = bytes.length / 2;
  const out = new Float64Array(n);
  for (let i = 0; i < n; i++) out[i] = bytes.readInt16LE(i * 2) / 32767;
  return out;
}

function close(actual, expected, tol, what) {
  assert.ok(
    Math.abs(actual - expected) <= tol,
    `${what}: got ${actual}, expected ${expected} (diff ${Math.abs(actual - expected)})`,
  );
}

describe('params agree with the Python reference', () => {
  test('constants match golden.params', () => {
    const p = golden.params;
    assert.equal(DEFAULT_PARAMS.sampleRate, p.sample_rate);
    assert.equal(DEFAULT_PARAMS.fftSize, p.fft_size);
    assert.equal(DEFAULT_PARAMS.hop, p.hop);
    assert.equal(DEFAULT_PARAMS.midiLow, p.midi_low);
    assert.equal(DEFAULT_PARAMS.midiHigh, p.midi_high);
    assert.deepEqual([...DEFAULT_PARAMS.harmonicWeights], p.harmonic_weights);
    assert.equal(DEFAULT_PARAMS.neighbourhoodCents, p.neighbourhood_cents);
    assert.equal(DEFAULT_PARAMS.maxNeighbourBins, p.max_neighbour_bins);
    assert.equal(DEFAULT_PARAMS.presentThresh, p.present_thresh);
    assert.equal(DEFAULT_PARAMS.extraMargin, p.extra_margin);
    assert.equal(DEFAULT_PARAMS.stabilityMs, p.stability_ms);
    assert.equal(DEFAULT_PARAMS.onsetFluxRatio, p.onset_flux_ratio);
    assert.equal(DEFAULT_PARAMS.onsetWindowFrames, p.onset_window_frames);
    assert.equal(DEFAULT_PARAMS.onsetFluxFloor, p.onset_flux_floor);
    assert.equal(DEFAULT_PARAMS.onsetRefractoryMs, p.onset_refractory_ms);
    assert.equal(DEFAULT_PARAMS.silenceRms, p.silence_rms);
    assert.equal(DEFAULT_PARAMS.octaveMode, p.octave_mode);
    assert.equal(DEFAULT_PARAMS.harmonicExclusion, p.harmonic_exclusion);
  });

  test('derived values match', () => {
    const d = golden.derived;
    close(binHz(DEFAULT_PARAMS), d.bin_hz, ROUNDING_FLOOR, 'binHz');
    close(frameIntervalMs(DEFAULT_PARAMS), d.frame_interval_ms, ROUNDING_FLOOR, 'frameIntervalMs');
    assert.equal(stabilityFrames(DEFAULT_PARAMS), d.stability_frames);
    assert.equal(windowSmearFrames(DEFAULT_PARAMS), d.window_smear_frames);
    assert.equal(onsetRefractoryFrames(DEFAULT_PARAMS), d.onset_refractory_frames);
  });
});

describe('transform', () => {
  test('Hann window is periodic, not symmetric', () => {
    // The classic port-drift bug: numpy.hanning uses divisor N-1.
    const w = hannPeriodic(8);
    const expected = golden.checks.hann_periodic_8;
    assert.equal(w.length, expected.length);
    for (let i = 0; i < w.length; i++) close(w[i], expected[i], ROUNDING_FLOOR, `hann[${i}]`);
    assert.ok(w[w.length - 1] > 0, 'periodic Hann has no trailing zero');
  });

  test('equal-tempered pitch matches', () => {
    for (const [midi, hz] of Object.entries(golden.checks.midi_to_hz)) {
      close(midiToHz(Number(midi)), hz, 5e-7, `midiToHz(${midi})`);
    }
  });

  test('band table matches — an off-by-one here shifts every chroma value', () => {
    const ex = new ChromaExtractor(DEFAULT_PARAMS);

    // Rebuild the same (midi, harmonic, lo, hi) view the exporter sampled.
    const seen = new Map();
    const rows = [];
    for (let b = 0; b < ex.bandNote.length; b++) {
      const midi = DEFAULT_PARAMS.midiLow + ex.bandNote[b];
      const h = (seen.get(midi) ?? 0) + 1;
      seen.set(midi, h);
      rows.push({ midi, harmonic: h, lo_bin: ex.bandLo[b], hi_bin_exclusive: ex.bandHi[b] });
    }

    assert.ok(golden.checks.bands.length > 0, 'golden has band rows');
    for (const want of golden.checks.bands) {
      const got = rows.find((r) => r.midi === want.midi && r.harmonic === want.harmonic);
      assert.ok(got, `no band for MIDI ${want.midi} harmonic ${want.harmonic}`);
      assert.equal(got.lo_bin, want.lo_bin, `${want.note} h${want.harmonic} lo bin`);
      assert.equal(
        got.hi_bin_exclusive, want.hi_bin_exclusive,
        `${want.note} h${want.harmonic} hi bin`,
      );
    }
  });
});

describe('chroma on embedded audio frames', () => {
  const ex = new ChromaExtractor(DEFAULT_PARAMS);

  for (const frame of golden.frames) {
    test(frame.id, () => {
      const samples = decodeSamples(frame.samples_b64_int16);
      assert.equal(samples.length, DEFAULT_PARAMS.fftSize);

      close(rms(samples), frame.expected.rms, TOL, 'rms');

      const spec = spectrum(samples, DEFAULT_PARAMS.fftSize);
      const { chroma, notes } = ex.compute(spec);

      for (let p = 0; p < 12; p++) {
        close(chroma[p], frame.expected.chroma[p], TOL, `chroma[${p}]`);
      }
      for (const [name, value] of frame.expected.top_notes) {
        const idx = notes.findIndex((_, i) => noteName(DEFAULT_PARAMS.midiLow + i) === name);
        assert.ok(idx >= 0, `note ${name} not in range`);
        close(notes[idx], value, TOL, `note ${name}`);
      }
    });
  }
});

describe('onset detector', () => {
  test('warm-up, flux floor, adaptive median and refractory all match', () => {
    const trace = golden.onset_trace;
    assert.equal(onsetRefractoryFrames(DEFAULT_PARAMS), trace.refractory_frames);
    assert.equal(MIN_HISTORY_FRAMES, trace.min_history_frames);

    const detector = new OnsetDetector(DEFAULT_PARAMS);
    const fired = [];
    trace.steps.forEach((step, i) => {
      const onset = detector.step(Float64Array.from(step.spectrum));
      assert.equal(onset, step.expected.onset, `step ${i} (${step.comment}) onset`);
      close(detector.lastFlux, step.expected.flux, TOL, `step ${i} flux`);
      close(detector.lastThreshold, step.expected.threshold, TOL, `step ${i} threshold`);
      if (onset) fired.push(i);
    });
    assert.deepEqual(fired, trace.expected_onset_indices);
  });
});

describe('verifier state machine', () => {
  test('arming, extras reset, stability counting and latching all match', () => {
    const trace = golden.verifier_trace;
    const params = withParams(DEFAULT_PARAMS, {});
    assert.equal(stabilityFrames(params), trace.stability_frames);

    const verifier = new Verifier(trace.target_pitch_classes, params);
    const notes = new Float64Array(params.midiHigh - params.midiLow + 1);

    trace.steps.forEach((step, i) => {
      const v = verifier.step(
        Float64Array.from(step.input.chroma),
        notes,
        step.input.onset,
        step.input.rms,
      );
      const want = step.expected;
      const where = `step ${i} (${step.comment})`;
      assert.equal(v.armed, want.armed, `${where} armed`);
      assert.equal(v.targetsPresent, want.targets_present, `${where} targetsPresent`);
      assert.deepEqual(v.extras, want.extras, `${where} extras`);
      assert.equal(v.framesHeld, want.frames_held, `${where} framesHeld`);
      assert.equal(v.confirmedNow, want.confirmed_now, `${where} confirmedNow`);
      assert.equal(v.latched, want.latched, `${where} latched`);
    });
  });
});
